### PR TITLE
Use better CBMC directory structure

### PR DESCRIPTION
**Pull request by danielsn**
*Issue #, if available:*

*Description of changes:*
Move the files from `.cbmc_batch/jobs` to the new standard name of `cbmc/proofs`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

### CODE REVIEW

**Comment by feliperodri** [comment]
@danielsn Should we move `cbmc/proofs` under `tests` like we do for s2n?

**Comment by danielsn** [comment]
> @danielsn Should we move `cbmc/proofs` under `tests` like we do for s2n?

@robin-aws I can see a few options
1. `/cbmc`, to parallel the `/saw`
2. `/verification/cbmc` and `/verification/saw`
3. `/tests/cbmc` and `/tests/saw` along with the unit and integration tests.

What do you prefer?

**Comment by feliperodri** [comment]
> > @danielsn Should we move `cbmc/proofs` under `tests` like we do for s2n?
> 
> @robin-aws I can see a few options
> 
>     1. `/cbmc`, to parallel the `/saw`
> 
>     2. `/verification/cbmc` and `/verification/saw`
> 
>     3. `/tests/cbmc` and `/tests/saw` along with the unit and integration tests.
> 
> 
> What do you prefer?

I vote for option **2**.

**Comment by robin-aws** [comment]
> > @danielsn Should we move `cbmc/proofs` under `tests` like we do for s2n?
> 
> @robin-aws I can see a few options
> 
> 1. `/cbmc`, to parallel the `/saw`
> 2. `/verification/cbmc` and `/verification/saw`
> 3. `/tests/cbmc` and `/tests/saw` along with the unit and integration tests.
> 
> What do you prefer?

I definitely vote against Option 3 - I get the motivation, but I think `tests/*` should be reserved for processes that actually execute the code (and not symbolically :))

Otherwise I don't have a really strong opinion. How loose would the definition of `verification` be? Would it include any other static analysis tools? Linters?

**Comment by karkhaz** [comment]
I vote for 2. (Will ping you internally about why).

**Comment by adpaco-aws** [comment]
I think this PR can be closed since #620 has been merged and #621 is on its way.

**Comment by feliperodri** [comment]
This PR has been superseded by #620.

**Pull request closed without merging**
